/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

#include<iostream>
#include<vector>

int main() {
	
	int init1 = 1;
	int init2 = 2;
	int sum = 0;
	int total = init2;
	
	while(sum < 4000000) {
		sum = init1 + init2;
		init1 = init2;
		init2 = sum;
		
		if(sum % 2 == 0) {
			total += sum;
		}
	}
	
	std::cout << total << "\n";
}
